### ISSUE TITLE
<CAPTION_TO_PHRASE_GROUNDING> raises error 

### ISSUE THREAD

**Issue by shadmehr-salehi** [askaresh/MS-Florence2#2]
CAPTION_TO_PHRASE_GROUNDING
raises : 
An error occurred: string indices must be integers.

**Comment by askaresh** [comment]
Fixed the issue and updated the code. Perform a pull and try agian

Result: {'<CAPTION_TO_PHRASE_GROUNDING>': {'bboxes': [[273.7919921875, 57.672000885009766, 336.76800537109375, 133.27200317382812]], 'labels': ['helmet']}}

Example:
![image](https://github.com/user-attachments/assets/83559dff-7761-425c-818e-a2f544c8de14)
